version: '2'
services:

  db:
    container_name: db
    image: postgres15-with-subzero
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=0.0.1
    ports:
      - "5432:5432"
      - "3000:3000"
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superuserpass
      - POSTGRES_DB=app
    volumes:
      - "./db:/docker-entrypoint-initdb.d"